name: 'example'
description: 'A sample command-line application.'
version: '1.0.0'
publish_to: 'none'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  database_universe_gas:
    path: '..'
  general_universe: '^0.0.0'
  google_apps_script_library: '^0.0.10'
  path: '^1.9.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: true
  is_private: false
  developers:
    - username: 'azkadev'
      note: ''
      social_medias:
        - 'https://github.com/azkadev'
dependency_overrides:
  general_universe:
    path: '../../../../galaxeus/app/general_developer_public_library_project/packages/general_universe'
  google_apps_script_library:
    path: '../../../general-developer/google_apps_script_library/package/google_apps_script_library'
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://youtube.com/{youtube_username}'
repository: 'https://github.com/{github_username}/{repository_name}'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/{youtube_username}'
