github:
  - 'azkadev'
  - 'HexaMinate'
  - 'nextgifto'
  - 'SpectaDev'
  - 'galaxeus'
  - 'AUTOMEXA'
  - 'meesagee'
  - 'archivon'
  - 'COINLOX'
  - 'envivore'
  - 'globalcorporation'
  - 'generalfoss'
  - 'general-developer'
