name: 'database_universe_gas'
description: 'A sample command-line application.'
version: '1.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  collection: '^1.19.0'
  general_universe: '^0.0.0'
  google_apps_script_library: '^0.0.10'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: 'azkadev'
      note: ''
      social_medias:
        - 'https://github.com/azkadev'
funding: []
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
